# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 阔阔的Blog
email: xinkuo.dev@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    阔阔的个人主页
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://blog.xinkuo.me" # the base hostname & protocol for your site, e.g. http://example.com
weibo_username: 小k阔阔
weibo_userid: "2663109067"
zhihu_username: 小k阔阔
zhihu_userid: "xkuokuo"
linkedin_username: xin-kuo
github_username:  xkuokuo

about_author: "我是阔阔。我住在一年三季都下雨的西雅图，目前在Amazon Web Service做AWS Lambda的软件开发。我喜欢解决问题，喜欢看小说，喜欢弹Ukulele。也欢迎访问我的<a href=\"https://xinkuo.me\">个人主页</a>。"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

show_excerpts: true

# Post link formatting
permalink: /post/:title.html

# Google Analytics
google_analytics: UA-121847857-1

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
